### ISSUE TITLE
Bug when multiplying less than 1

### ISSUE THREAD

**Issue by scevec** [jeyries/calculator#1]
I was trying to calculate how much the sales tax would be for an item. I attempted to multiply: 39.99 x .075 and it showed the product as 1599.23. I thought maybe I pressed a wrong button so I tried again and paid more attention. 
I entered 39.99 x .075 and I noticed that the display showed 39.99075 in the upper right and 39.99 x 39.99075 in the upper left. 
I tried again and put a leading 0 in front of .075 and it calculates just fine. 
So trying to multiply by a number less than 1 and leaving out the leading 0, the calculation does not work properly. I’ve tested on a couple other calculators and they handle it fine. 

![A6F2D044-7BAD-4C4A-BDF2-8B428ED30B60](https://user-images.githubusercontent.com/28810601/136682218-93c055a8-7aa7-4ff4-929d-54404e090052.png)

![AF5D4E05-C9BD-4E4E-9C9E-E284BBD639A8](https://user-images.githubusercontent.com/28810601/136682219-e39beb63-3e13-451b-8e22-b4a89d40322e.png)

![1BFE4AA5-3099-493F-8D62-E7A034F3F9BC](https://user-images.githubusercontent.com/28810601/136682221-61e89568-749f-4846-9540-73aba3c991a3.png)

**Comment by scevec** [comment]
Also, I wanted to thank you for doing something that Apple chose not to. And no ads no charge for the app is awesome!

**Comment by jeyries** [comment]
Hi ! Thanks for your bug report. This specific bug has now been fixed. Please use the 1.0.7 version that is available on the App Store. 
 Regards, Julien.
