### ISSUE TITLE
Simple typo

### ISSUE THREAD

**Issue by raphpay** [jeyries/calculator#2]
There is a 's' missing in 'Mes autres application' text in the menu.

**Comment by jeyries** [comment]
Thanks ! Bien vu ;-)

**Comment by OfficialPIGZ** [comment]
Hello, petit soucis au niveau UI de la calculatrice.. ça dépasse un peu.
iPad Pro M1 11 pouces![image](https://user-images.githubusercontent.com/42617645/181624504-ab86bbdd-1387-4a4e-be0e-1b02e1e55ae6.png)

**Comment by jeyries** [comment]
Fixed !
