### ISSUE TITLE
[Feature Request] Add support for slide over and split view for the iPad

### ISSUE THREAD

**Issue by Lundeful** [jeyries/calculator#6]
Thanks for creating a good calculator app for the iPad. If you have the time I have a feature request.

It would be great to have support for the slide over or split view feature on iPad. That way we can use the calculator while multi-tasking properly.

I don't know if what is needed is to add some reponsive design or if there is some more complex work. 

Maybe the calculator can shrink in size and the history sit above the calculator so the width is smaller.

Thanks again 😄

**Comment by jeyries** [comment]
Well, the app was getting rejected by the App Store review team because of the portrait mode :
"Your app is too similar to native Calculator app, which creates a misleading association with Apple products."

**Comment by jeyries** [comment]
Anyway, thanks for the feedback, It is always appreciated :-)

**Comment by Lundeful** [comment]
Hmm. The iPad does not have a native calculator app though so they shouldn't reject it there at least. But maybe it's not worth it for just the iPad? I don't know which platform downlands your app the most.

Thanks anyway 😃
